### ISSUE TITLE
Language, palette and a crash error

### ISSUE THREAD

**Issue by EddieMattos** [iso4free/spedit#16]
The interface translation isn't loading here, the palette presets doesn't auto load after reopen the program. And I'm getting the following error after an empty warning window appears:
Project spedit raised exception class 'External: Unknown exception code 8'.

 At address 7E9FA6 

I'm using Ubuntu 22.04.1 LTS

**Comment by iso4free** [comment]
Language and autoload presets fixed.
Under what circumstances does the Unknown exception occur?

**Comment by EddieMattos** [comment]
It occurs at the moment I drag and drop or open an image. If I close the warning it reapears when the cursor is moved. The empty warning window seems to have a text box and clickable buttons, at first i thought it was a add a new layer window

**Comment by iso4free** [comment]
Could You send me an the image You try to open?

**Comment by iso4free** [comment]
I found the solution - if checkers size was saved as 0 then error occurs. Now it fixed.
