### ISSUE TITLE
Tool windows disappear with fullscreen canvas

### ISSUE THREAD

**Issue by EddieMattos** [iso4free/spedit#6]
I like to work with the canvas in full screen, but with this the tool windows are in the background. I think it might be interesting to implement functions to activate windows always on top.. perhaps an icon for each tool window.

**Comment by iso4free** [comment]
Maybe try to integrate the tool windows into the main window and immediately run the program expanded to the entire screen?

**Comment by iso4free** [comment]
Fixed.
