### ISSUE TITLE
Mascot

### ISSUE THREAD

**Issue by EddieMattos** [iso4free/spedit#7]
Spedit's mascot is very interesting, it looks like a cross between a bat and a demon. But it seems to be very old-fashioned by today's standards when it comes to pixel art and the operating system. So I took the liberty of updating the original artist's incredible work.
Along with a colored example.

![photo_2022-12-03_02-15-46](https://user-images.githubusercontent.com/73829421/205426749-23d8afc2-eb60-4df0-9e89-839a81b13b2b.png)

**Comment by iso4free** [comment]
I love it and it's very cool and modern! I'm ready to change the app icon, just send me the appropriate resource file for replacement.
